spring.datasource.url= jdbc:postgresql://dpg-d6doebsr85hc73c1rvtg-a.oregon-postgres.render.com:5432/java_web_employee_managment_database
spring.datasource.username=java_web_employee_managment_database_user
spring.datasource.password=c1Pl2yX4JRxiuJdWd0l3xyxtxjiSDohl
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
server.error.include-message=always